# PostgreSQL Datasource Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/crud_java
spring.datasource.username=postgres
spring.datasource.password=mysecretpassword

# Tell Hibernate to not manage the schema, Flyway will do it
spring.jpa.hibernate.ddl-auto=none

# Tell Flyway where the database is
spring.flyway.url=${spring.datasource.url}
spring.flyway.user=${spring.datasource.username}
spring.flyway.password=${spring.datasource.password}
